services:
  mail-archiver:
    build:
      context: .
    env_file:
      - ./config/.env
    volumes:
      - /mnt/mail-archive:/data
      - ./state:/state
      - ./config:/app/config:ro
    restart: "no"
